# Generated by Django 5.2.2 on 2025-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDFname', models.CharField(max_length=255)),
                ('Authorname', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
            ],
        ),
    ]
