# Generated by Django 5.2.2 on 2025-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFStorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
